[package]
name = "json_parser"
version = "0.1.0"
authors = ["timothy-tianmu <tianmu_19970924@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
